
" BASIC config
"> Modes
">> do not use vi compatibility mode. 
    set nocompatible
"> Cursor and Mouse
">> show cursor in any mode. allow use of mouse in any mode. fast scroll.
    set ruler
    set mouse=a
    set ttyfast
"> Search
">> make search case-insensitive. capital letters make search case-sensitive
    set ignorecase 
    set smartcase
"> Window
">> show line numbers. show current mode. allow reuse the same windows.   
    set number 
    set laststatus=2 
    set hidden
">> set left margin. Show filename in the terminal tab/window title 
    set numberwidth=2
    set title
"> Other
">> open hyperlinks in chrome
    let g:netrw_browsex_viewer= "google-chrome -P user"
">> skip .swp files message
    autocmd SwapExists * let v:swapchoice = "e"

" PLUGIN config
"> Pathogen as the Plugin Installer 
    execute pathogen#infect()
"> VimTex
">> choosing the pdf reader and the compiler configuration. avoiding the log box.
    let g:tex_flavor = 'latex'          
    let g:vimtex_view_method = 'zathura'  
    let g:vimtex_compiler_latexmk= {'options' : [ 
        \'-pdf', 
        \'-shell-escape',
        \'-verbose', 
        \'-file-line-error', 
        \'-synctex=1', 
        \'-interaction=nonstopmode',
        \],}
">> .bibtex autocomplete (doesn't working)
    let g:vimtex_quickfix_enabled = 0   
    let g:vimtex_complete_bib = {
        \'menu_fmt': '[@type] @author_all (@year), "@title"'
        \}
">> using f5 to compile and open the resulting .pdf
    autocmd filetype tex nnoremap <buffer> <f5> :VimtexCompile<cr> i
    autocmd filetype tex inoremap <buffer> <f5> <esc> :VimtexCompile<cr> i
"> Commentary
">> comment current line in insert mode with ctrl+l. comment current paragraph with ctrl+p  
    inoremap <c-l> <esc>gcc i
    inoremap <c-p> <esc>gcap i
    nnoremap <c-l> <esc>gcc i
    nnoremap <c-p> <esc>gcap i
"> SnipMate
">> setting the newer version to avoid "SnipMate deprecated" message.
    let g:snipMate = { 'snippet_version' : 1 }
">> ctrl+e and ctrl+b to emphasized and bold text
    autocmd filetype tex inoremap <buffer> <c-e>  \em<tab>
    autocmd filetype tex inoremap <buffer> <c-b> \bf<tab>
    autocmd filetype tex vnoremap <buffer> <c-e> c\emph{<esc>"+pi} 
    autocmd filetype tex vnoremap <buffer> <c-b> c\emph{<esc>"+pi} 
"> Calendar-Vim
">> ctrl+up and ctrl+down to change month. < and > to change month
    let g:calendar_keys = {
    \'goto_next_month': '<tab>',
    \'goto_prev_month': '<s-tab>',
    \'goto_next_year': '>',
    \'goto_prev_year': '<',
    \}
"> VimWiki
">> setting wiki paths and names. setting Markdown syntax
        let g:vimwiki_list = [
                          \{ 'path': '~/files/me/org/',
                          \  'syntax': 'markdown',
                          \  'ext': '.md',
                          \  'name': 'org' },
                          \{ 'path': '~/files/me/org/dev',
                          \  'syntax': 'markdown',
                          \  'ext': '.md',
                          \  'name': 'dev' },
                          \{ 'path': '~/files/me/org/mpc',
                          \  'syntax': 'markdown',
                          \  'ext': '.md',
                          \  'name': 'mpc' },
                          \{ 'path': '~/files/me/org/research',
                          \  'syntax': 'markdown',
                          \  'ext': '.md', 
                          \  'name': 'math' },
                          \{ 'path': '~/files/me/org/pessoal',
                          \  'syntax': 'markdown',
                          \  'ext': '.md',
                          \  'name': 'me' },
                          \{ 'path': '~/files/nerd/doc',
                          \  'syntax': 'markdown',
                          \  'ext': '.md',
                          \  'name': 'doc' }
                        \]
">> disabling default keybindings
    let g:vimwiki_key_mappings =
                            \ { 'all_maps':1 ,
                           \   'global': 0,
                            \   'headers': 1,
                            \  'text_objs': 0,
                            \   'table_format': 0,
                            \   'table_mappings': 0,
                            \   'lists': 1,
                            \   'links': 0,
                            \   'html': 0,
                            \   'mouse': 0,
                            \ }
">> "ctrl+enter" to follow links. "ctrl+bksp" to go back
    autocmd filetype vimwiki nnoremap <c-[> :VimwikiFollowLink<cr>
    autocmd filetype vimwiki inoremap <c-[> <esc>:VimwikiFollowLink<cr>
    autocmd filetype vimwiki nnoremap <c-]> :VimwikiGoBackLink<cr>
    autocmd filetype vimwiki inoremap <c-]> <esc>:VimwikiGoBackLink<cr>
">> go to index.md with "ctrl+1". Go to main index.md with "ctrl+0"
    autocmd filetype vimwiki nnoremap 0 :! vim ~/files/me/org/index.md<cr> 
    autocmd filetype vimwiki nnoremap 1 :VimwikiIndex<cr>
">> "rn" to rename a file
    autocmd filetype vimwiki nnoremap rn :VimwikiRenameFile<cr>
">> "d" to delete a file
    autocmd filetype vimwiki nnoremap d :VimwikiDeleteFile<cr>
 

"TEXT config
"> Indentation
">> auto indent for plugins and files. allow backspacing auto indented paragraphs.
    filetype plugin indent on  
    filetype indent on
    set autoindent
    set breakindent
    set backspace=indent,eol,start
    set shiftwidth=4 
">> tab maximal/default space size. convert tab space in white space.  
    set tabstop=8                 
    set softtabstop=4           
    set expandtab
"> Folding
">> prevent folding
    set nofoldenable
"> Highlight
">> enable 256-colors. allow syntax/search highlight. highlight cursor line.
    set t_co=256
    syntax enable
    set hlsearch
    set cursorline    
">> set default color scheme.
    colorscheme iceberg
">> allowing to set a color scheme for a fixed filetype.
    autocmd BufWinEnter,FileType tex colorscheme vimtex-colors
"> spelling
">> enable spell checker in specific languages. fixing spell language.
    autocmd FileType latex,tex,md,markdown setlocal spell
    set spelllang=en_us,pt_br
">> ctrl+n to add word to dictionary
    nnoremap <c-n>zg i
    inoremap <c-n> <esc>zg i
">> ctrl+b to display the spell hints
    nnoremap <c-b> z=i
    inoremap <c-b> <esc>z=i

"> Mailing
">> set up syntax highlighting for mutt
    au bufread,bufnewfile .followup,.article,.letter,/tmp/pico*,nn.*,snd.*,/tmp/mutt* :set ft=mail

" HOTKEYS config
"> Moving
">> esc in normal mode move to insert mode
    nnoremap <esc> i
">> tab in normal mode
    nnoremap <tab> i<tab><esc>
">> a in normal mode move to beggining of line
    nnoremap a ^hh  
">> use cursor arrows to move through long lines, ignoring wrapping.
    inoremap <silent> <down> <c-r>=pumvisible() ? "\<lt>down>" : "\<lt>c-o>gj"<cr>
    inoremap <silent> <up> <c-r>=pumvisible() ? "\<lt>up>" : "\<lt>c-o>gk"<cr>
    nnoremap <down> gj
    nnoremap <up> gk
">> home/end button goes to top/end of the page
    inoremap <home> <esc> ggi
    nnoremap <home> ggi
    inoremap <end> <esc> GGi
    nnoremap <end> GGi
"> Search
">> use ctrl+f to search. ctrl+down to move along results.
    nnoremap <silent> <c-f> /
    inoremap <silent> <c-f> <esc>/
    snoremap <c-down> n
"> Editing
">> delete with backspace in normal mode and visual mode 
    vnoremap <bs> d<esc>i
">> ctrl+x to cut, crtl+c to copy and ctrl+v to paste (in the normal mode)
    nnoremap <c-k> <c-v>
    inoremap <c-k> <esc><c-v> 
    vnoremap <c-x> c
    inoremap <c-x> <esc>vc
    vnoremap <c-c> "+yi
    inoremap <c-v> <esc> "+pi
">> copy and paste directly to clipboard
    set clipboard=unnamedplus
">> ctrl+z to undo and ctrl+r to redo
    noremap <c-z> u
    inoremap <c-z> <c-o>u
    inoremap <c-r> <esc><c-r>i
"> Selecting
">> use shift+arrows to select text.
    nnoremap <s-up> v<up>
    nnoremap <s-down> v<down>
    nnoremap <s-left> v<left>
    nnoremap <s-right> v<right>
    vnoremap <s-up> <up>
    vnoremap <s-down> <down>
    vnoremap <s-left> <left>
    vnoremap <s-right> <right>
    inoremap <s-up> <esc>v<up>
    inoremap <s-down> <esc>v<down>
    inoremap <s-left> <esc>v<left>
    inoremap <s-right> <esc>v<right>
">> use ctrl+a to select all
    nnoremap <c-a> ggvGG$
    inoremap <c-a> <esc>ggvGG$
"> General
">> save with ctrl+s
    nnoremap <c-s> :w!<cr>i
    inoremap <c-s> <esc> :w!<cr>i
    vnoremap <c-s> <esc> :w!<cr>
">> quit without saving with ctrl+q
    nnoremap <c-q> :q!<cr>
    inoremap <c-q> <esc> :q!<cr>
    vnoremap <c-q> <esc> :q!<cr>

