# PROMPT
## display time and the current directory
    time="33m`date +%H:%M`"
    time1="\[\033[$time\]"
    dir1="\[\033[32m\]\w\[\033[00m\]"
    PS1="$dir1\$ "

# ALIASES
## include aliases file
    source ~/files/config/linux/bash/bash_aliases

# INCLUDES
## Sync-Sh
### sync local dirs with git initialize copies
### push the content to github or gitlab
#    if [ -f ~/files/nerd/dev/sh/sync-sh/sync ]; then
#        source  ~/files/nerd/dev/sh/sync-sh/sync
#    fi
    if [ -f ~/files/nerd/dev/sh/sync-script/sync-script.sh ]; then
        source  ~/files/nerd/dev/sh/sync-script/sync-script.sh
    fi
    alias bkp="bash ~/files/nerd/dev/sh/sync-script/init.sh" 

## Cvt-Sh
### intuitive cli for pandoc translator
    if [ -f ~/files/nerd/dev/sh/cvt-sh/cvt ]; then
        source  ~/files/nerd/dev/sh/cvt-sh/cvt
    fi

## Trnsl-Sh
### intuitive cli for translate-shell
    if [ -f ~/files/nerd/dev/sh/trnsl-sh/trnsl.sh ]; then
        source  ~/files/nerd/dev/sh/trnsl-sh/trnsl.sh
    fi
## Easycl-Sh
### easy command line for bash
    if [ -f ~/files/nerd/dev/sh/easycl-sh/nav ]; then
        source  ~/files/nerd/dev/sh/easycl-sh/nav
    fi
    if [ -f ~/files/nerd/dev/sh/easycl-sh/mk ]; then
        source  ~/files/nerd/dev/sh/easycl-sh/mk
    fi
## Vim-Org
      source  ~/.config/vim-org/script/org

